# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassignment',
            name='hotel_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productassignment',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
    ]
