# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160810_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(default=''),
        ),
    ]
