# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username'),
        ('users', '0003_auto_20160810_1131'),
    ]

    operations = [
    ]
