# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('docfile', models.FileField(upload_to=upload.models.get_file_path)),
            ],
        ),
    ]
